### ISSUE TITLE
Team 8 - vuln2 issue

### ISSUE THREAD

**Issue by joon731** [teddyyeo/KUsino#29]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA0aC2syHCVy2AQf/fFSpaJeiX8bHmQul2M8OLjt+Rb9zXya1TwCdOMEcQ2lQ
KRyjY1QuRhwnXObJV9cyej2cg/yhMVBA+r8cQbvXoMU6oY/DTKsQo1tkbmRN6K14
ilefDx4XOpDfGASTFQefgQtAQ1Ha1YfESNSSu9laOf3t5zmbZ+B5geSkwKLcbpKm
Z5H38/noCGDGgHk4m3RcOPFHUgqIicwNSUlHOg7pm8FkAxA2nq/CI0YJFspY/SoG
mqCIakw3K8I8Fc8UUHDFaKzp0SzMVALr+C/8oEbiUpQTWIhSMu+T/AlTGSZTIvgU
IfoG6w1/f6UKh+T1vNQwcRC4NQ6k5ytt7J1ukDQiNIUBDANHZLRJ/h6DygEH+wfP
4e/CU6VxBARO6NDNaiGxs5ldvyH2K4iECorj8DrEoJ7IKWgHxahXZiBonlI6Z/8L
7sq5X3mPL3AFAVRbonWoNLvO2IiAnuVtI04lal42Xbe1hu8uMSPwgvjc72cTNiLs
CF5EOONlSSm9PufWt0qS2qDUEOMBndbLBDYZB5ruPW2ZnVI3REN2C/5sOUvv0XDE
Ag5+YIiMuS7zhqnTf0nyLplOi7u/KVehzCWKOR7YuF1AolVqD6jle3BNpDwTvZrk
OM5iNv3J63R5xEN3G0TMhHwGbdNsU1eLuMdR+5zZoqt4IPx0drAVWSSS9JNgS21R
p8RdoZdMT4KOklMSjxmFAQwDMURL2j9atxABB/9PMT88aWBBoMo/Cfqe9q0voXbM
HeKJg+S3yPklJAwhYmS8WBdXopZ+JfrYNLXoYQtX0GjILw2lKtxx+ho98q+Z3nDi
AG6NC3ZMn0blHqOAZ+7k1Kf55t005MLn3eMGaveSFtPloQlIdNbFlHTNHHtszTes
mXlsNyqpIeJrftZ/mDvbqD/Tjq8gcMZA7hVI3mSG8OWuYxKePHhGJEArmBaWE+NW
fcdT5Lchhg1rJJrnZ2e1BPHGizSIQ4+kRxhiQZtkc6Xe4plXlhy7VlA0+lbQySLa
9NF9XJlG77S2BL5Ssqlxz/MGM65HEyvbvbqTkwA3RKAgAntIy9+HNDOBobtn0ukB
jWtfUSNejpPiCw6zKbXaPv+n2Um8PsM4LurtYMssNxBAmZk/+akTWZ9GvZZyjRpP
Fyz2pmADHeBEi48W29S7z3H+19fC+ZiETCjv71xy9w+8F3fqbnsmZOeyTx5fDHec
EMDyHY65+jqXpiP5CMDZd+pWvC9vdYOickx2uWFxPqM4r1ETxWuprdhgpbxOtlo0
z83+9Og2giaKyRntgBsdomtCPjoRMpQOin8rc9CmwNYjCuyt0q+f0KSjLk2amQPT
pG6wncsE9rNwYD2HlhVmmRWmcfL6D9Bc9ClkG5g2qAfr+aJji9JY0OOaFocaqu+W
BOWG7UW8/rKz01rzso3ZXcV3Ef/NXdxa+Q+C2UEGusYd/CuywhPxndUZNx42cGly
3Z21vn+6lmnu9skzpGd8DU6DkqhBdK/3MmKPS4XltaqGtWAWBbiwsP+WLDpvrBRk
OkOz6jaqqRc8e7t53pkiV3h57iOrc/F00N8obAm/vewONKDdA9VJI3NKmVn4UBlx
21BV1sxCXv+6X1W+hlxfm2quhJaFsHCNWgWquhXk52rN+UYFhiXh0998xyvB1XKt
LRWBFpq/m6ZDwFtF5mxBoY3KHxSnYstFxRf5clwWIgzDhpCH5NP1fgzOUNvHObne
mmEJUOXntSyqxTEK89T6UxWxk9A9CWiAJ7GdTjPnklRTsLJXQ5SVqLOLrCo6C0RG
H5G8tQdonn5oGBWaQPlUFFtqD7eoZsA+A5cbTK9Te/FL5Y8m67cmhmJgy/dyftYQ
hZrRypQCzQWfBGPoNnD0TVhpVUU=
=aehh
-----END PGP MESSAGE-----

**Comment by chaum11** [comment]
It is same with Team 8-vuln1 issue. Would you check it once again? 😊

**Comment by joon731** [comment]
I apologize, I uploaded twice. I will delete and update properly :)

-----Original Message-----
